### PR TITLE
Passing state to `handle_setup`

### PR DESCRIPTION
**Pull request by Odaeus**
Resolves issue #64.

Please review and let me know if the code fits to how you want it to work!

### CODE REVIEW

**Comment by nsweeting** [comment]
Thanks @Odaeus! I will try and review this today.

**Comment by Odaeus** [comment]
@nsweeting I've pulled out the "optional queue opt" to a separate commit and added something to return a clear error if there's no queue name by the time it reaches `consume`. In theory it could automatically declare if there's no queue but that might be confusing behaviour. Obviously this commit can be discarded if you really want to keep the option as required.

**Comment by Odaeus** [comment]
Hey @nsweeting, just wanted to let you know that I'm planning to merge this and related changes into the master branch of my fork this week. Still happy to make any changes when requested, with the aim that we will eventually be using your official version.

**Review by nsweeting — CHANGES_REQUESTED** [review]
Since we are still a pre-1.0 release - I would be fine with making this a "breaking" change in order to maintain this as a cleaner implementation. As long as we make sure to note the change in the release notes.

Based on the above - I think we can drop support for `handle_setup/2` and only deal with `handle_setup/1` with the state being passed. The expected return value should  be `{:ok, state}` .

I don' t think we need to support a `:skip` return value. Unless you have a requirement I don't see right now?

**Comment by Odaeus** [comment]
Sorry for the delay on this! I've removed `.handle_setup/2` support. I've done it for both `Consumer` and `Producer`, but if you wanted the latter kept feel free to drop the commit.

Hopefully I've updated all the documentation in the right places.

**Comment by nsweeting** [comment]
> Sorry for the delay on this! I've removed `.handle_setup/2` support. I've done it for both `Consumer` and `Producer`, but if you wanted the latter kept feel free to drop the commit.
> 
> Hopefully I've updated all the documentation in the right places.

Looks great @Odaeus! Will merge and cut a new release. Thanks.

**Review by nsweeting — APPROVED** [review]

**Comment by nsweeting** [comment]
@Odaeus Had to submit PR https://github.com/nsweeting/rabbit/pull/73 to support `Rabbit.ConsumerSupervisor.handle_setup/1` which I missed within this PR. No big deal though. Version 0.13.0 should be available now - https://hex.pm/packages/rabbit/0.13.0.

**Comment by Odaeus** [comment]
Thanks so much!

**Pull request merged**
